### ISSUE TITLE
Volume configuration for civiCRM development

### ISSUE THREAD

**Issue by Pitt-Pauly** [djcf/civicrm-docker#3]
Hi,
First off thank you for having created this project! It's really cool to have a civiCRM and Drupal install up and running in a few commands!

I'm just starting to contribute to the civiCRM project as a developer and I would love to use docker to build my development environment. However I am not super familiar with docker just yet and I wondered how it would be possible to expose the civiCRM and Drupal code so I could develop using your docker-compose app. Or put differently, how can I install civiCRM by pulling my code from a git repository rather than form an official site?
One option I suppose would be to map a local volume to be used by the docker image, in which I would have the civiCRM code (pulled from the git repo), and then rebuild the docker image every time I want to roll out the updated code. Would that make sense?

Cheers!

**Comment by dm-coding** [comment]
I'm sorry I missed this earlier.

What I would do, is add a step in `build/install.sh` which pulls down a fresh copy of CiviCRM code using parameters supplied to the container environment by docker. That way, whenever the buildkit image runs (once, on first start-up, to install the database), it first checks out the relevent code from github.

Richarvey's nginx container may already be set up to do this. Check his documentation first because it could actually be that simple.
